//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EARGE.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class MoneyIncome
    {
        public int Id { get; set; }
        public int TeamMemberId { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public bool IsApproved { get; set; }
        public int CreateUserId { get; set; }
        public System.DateTime CreateDate { get; set; }
        public bool Deleted { get; set; }
    
        public virtual TeamMember TeamMember { get; set; }
        public virtual TeamMember TeamMember1 { get; set; }
    }
}
