//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EARGE.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public Project()
        {
            this.MoneyOutgoings = new HashSet<MoneyOutgoing>();
            this.ProjectTasks = new HashSet<ProjectTask>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public decimal Budget { get; set; }
        public int ProjectOwnerMemberId { get; set; }
    
        public virtual ICollection<MoneyOutgoing> MoneyOutgoings { get; set; }
        public virtual TeamMember TeamMember { get; set; }
        public virtual ICollection<ProjectTask> ProjectTasks { get; set; }
    }
}
