//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EARGE.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectTask
    {
        public ProjectTask()
        {
            this.MoneyOutgoings = new HashSet<MoneyOutgoing>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> PublishedDate { get; set; }
        public Nullable<int> AssignedMemberId { get; set; }
        public string TargetGroups { get; set; }
        public int StatusId { get; set; }
        public Nullable<System.DateTime> AssignedDate { get; set; }
        public Nullable<System.DateTime> CompletedDate { get; set; }
        public decimal HoursEffort { get; set; }
        public int ProjectId { get; set; }
        public decimal BudgetAmount { get; set; }
        public string Notes { get; set; }
    
        public virtual ICollection<MoneyOutgoing> MoneyOutgoings { get; set; }
        public virtual Project Project { get; set; }
        public virtual TaskStatus TaskStatus { get; set; }
        public virtual TeamMember TeamMember { get; set; }
    }
}
