//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EARGE.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysLog
    {
        public int Id { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int LogTypeId { get; set; }
        public Nullable<int> LogCreatedByMemberId { get; set; }
        public int TargetObjectId { get; set; }
    
        public virtual SysLogType SysLogType { get; set; }
        public virtual TeamMember TeamMember { get; set; }
    }
}
