//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EARGE.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeamMemberRole
    {
        public int Id { get; set; }
        public Nullable<int> TeamMemberId { get; set; }
        public Nullable<int> RoleId { get; set; }
    
        public virtual Role Role { get; set; }
        public virtual TeamMember TeamMember { get; set; }
    }
}
